chore(script): update push-protection

diff --git a/push-protection b/push-protection
--- a/push-protection
+++ b/push-protection
@@ -2,16 +2,16 @@
 
 while read local_ref local_sha1 remote_ref remote_sha1
 do
-  for branch in "master" "production"; do
+  for branch in "master" "production" "release"; do
     if [[ "${remote_ref##refs/heads/}" = "${branch}" ]]; then
-    echo "WARNING: Pushing to important branch, are you sure? [y/N]"
+    echo "Warning: You are pushing to the remote important branch, are you sure? [y/N]"
 
       exec < /dev/tty
       read ANSWER
 
       case $ANSWER in
-        "Y" | "y" | "yes" | "Yes" | "YES" ) echo "OK: Pushing starts...";;
-        * ) echo "Pushing canceled";exit 1;;
+        "Y" | "y" | "yes" | "Yes" | "YES" ) echo "OK. push start.";;
+        * ) echo "push failed.";exit 1;;
       esac
       exit 0
     fi
